### PR TITLE
Moved tidy data concept up

### PR DESCRIPTION
**Pull request by lwjohnst86**
It doesn't flow very nicely where it was previously.

### CODE REVIEW

**Comment by joelostblom** [comment]
Are you thinking of it like an intro to tidy data? Saying what it is and briefly showing how to do it, but mostly staying with already tidied data frames? I am asking because I think too much reshaping can get quite complex quickly.

**Comment by lwjohnst86** [comment]
Yes, definitely only the overall concepts of tidy data, since dplyr emphasizes that concept. (I think maybe even tidyr would be useful to include since they play nicely off of each other)

**Comment by joelostblom** [comment]
Ok I will include it and then we can adjust based on your feedback.

**Comment by joelostblom** [comment]
I have included `gather` and `spread` in assignment 3 and will have them in the lecture as well.

**Pull request merged**
