### PR TITLE
Lec14 fix

### PR DESCRIPTION
**Pull request by James-S-Santangelo**
Fixing issue with local PDF knitting due to incompatibility with DiagrammeR. Issue and fix are described [here](https://github.com/rich-iannone/DiagrammeR/issues/133).

### CODE REVIEW

**Comment by QuLogic** [comment]
Can you [use `rsvg::rsvg_pdf`](https://github.com/rich-iannone/DiagrammeR/issues/133#issuecomment-284370996)? `webshot` is so heavy...

**Comment by James-S-Santangelo** [comment]
Yeah I think I can get that to work. No time just yet but I'll get to it soon. No rush on this one since PDF is already available to students.

**Comment by mbonsma** [comment]
Can I / should I merge this?

**Comment by James-S-Santangelo** [comment]
Feel free to. It won't break anything. I never got around to making it more efficient but I can make a note of it for next year/the next release.

**Pull request merged**
