### PR TITLE
Remove commented section about tab complete to fix uneven commenting

### PR DESCRIPTION
**Pull request by joelostblom**
Maybe these comments are the reasons why the images are not currently showing up at https://uoftcoders.github.io/rcourse/lec01-introduction.html? Although probably not... any idea why the plot images are not showing up on the site anymore @lwjohnst86 @aays ?

### CODE REVIEW

**Comment by joelostblom** [comment]
Maybe just something wrong in the last build and we only need totrigger a rebuild and see if it works?

**Comment by lwjohnst86** [comment]
You want my review on the commit or on why the image isn't showing?

**Comment by lwjohnst86** [comment]
I looked into it a bit and I'm not entirely sure why. It could be two things: The code chunk might need to be named (not likely) and maybe when the `output: pdf_document` is added to the top it changes things...?

which by the way, you don't need that output option in the YAML header @aays and @joelostblom

**Comment by lwjohnst86** [comment]
@joelostblom the images work now!

**Comment by aays** [comment]
Good catch @joelostblom - though seems I'm a bit late to the party (thanks for the fix @lwjohnst86 !) 

Might as well get rid of that commented section all the same however, just to keep things clean.

**Comment by joelostblom** [comment]
Great thanks guys!

**Pull request merged**
